### ISSUE TITLE
Document live streaming for Core Dev Calls

### ISSUE THREAD

**Issue by bmann** [ethereum-cat-herders/PM#29] opened 2019-04-04 02:02 UTC
On Twitter / Reddit, @souptacular announced that only a few people know how to livestream. 

It would be good to document this and give other people permission. 

See https://en.ethereum.wiki/infrastructure#all-core-dev-calls for a start and some questions

**Comment by Souptacular** [comment] 2019-04-04 03:54
On YouTube permissions, if you have permission to livestream you also have permission to delete videos. It is a huge risk to allow more than a few people to have that access.

Alternatively, we can have someone stream it to their own account and then afterwards we can upload it to the ethereumfoundation YouTube channel.

**Comment by bmann** [comment] 2019-04-04 03:58
This is the research I did on managing a brand account / permissions for managers https://support.google.com/youtube/answer/4628007?hl=en

If the ethereumfoundation account is not set up as a brand account, then it should be.

Also, if that's the only source of those videos, maybe we can download them and archive them somewhere else?

I think @timbeiko said he could do this. Do you trust him to have access for 24 hours? Alternately, Tim, are you comfortable streaming on your own account? 

Note: that I don't really care that strongly about whether or things get streamed on April 12th. I _do_ care about community infrastructure being documented so we know who has control of what and what the backup plan is.

**Comment by Souptacular** [comment] 2019-04-04 04:21
I'll talk to Tim about streaming it for April 12th. We can also move the videos off of Ethereum Foundation YouTube infra.

**Comment by Souptacular** [comment] 2019-04-04 04:21
Whoops closed it.

**Comment by timbeiko** [comment] 2019-04-04 12:45
I'm happy to try and stream it. IMO it'd be a bit weird for it to be on my personal account. I can imagine people being put off by that, but if it's better than nothing, sure. Hudson and I have a call scheduled today, we can go over that during it and report back here :-)

**Comment by lrettig** [comment] 2019-04-04 13:53
Can we just set up a new "allcoredevs" brand account? And Twitter too. And blog.

It's time.

**Comment by timbeiko** [comment] 2019-04-04 14:05
I think it maybe makes sense to keep the AllCoreDevs calls on the EF account, but maybe find a way to broaden access. Re: Twitter, someone registered `EthCoreDevs` and I managed to snag `AllCoreDevs`. Not sure if there is a way to allow multiple people on it. For a blog, isn't that EthMagicians 😛?

**Comment by lrettig** [comment] 2019-04-04 14:08
There is no EthMagicians blog. And I think there might be value in having a more quasi-official blog where the core devs can post things, apart from EF. It's not urgent.

You can share a Twitter account using Tweetdeck!

Why do you think it makes sense to keep the calls on the EF account?

**Comment by timbeiko** [comment] 2019-04-04 14:22
> You can share a Twitter account using Tweetdeck!

Good to know! Not sure what the next steps would be here. How do we get rough consensus on whether this is valuable or whether it just adds noise?

> Why do you think it makes sense to keep the calls on the EF account?

The reach, mostly. Also, if we can set up multiple users on an `AllCoreDevs` account, then why shouldn't we do just that with the EF one?

**Comment by sneg55** [comment] 2019-04-04 15:13
> Can we just set up a new "allcoredevs" brand account? And Twitter too. And blog.
Maybe even stand-alone site for Allcoredevs?

**Comment by Souptacular** [comment] 2019-04-04 16:05
> > Why do you think it makes sense to keep the calls on the EF account?
> 
> The reach, mostly. Also, if we can set up multiple users on an `AllCoreDevs` account, then why shouldn't we do just that with the EF one?

The issue is that the Ethereum Foundation YouTube account is a brand account and so anyone who has access to the brand account can delete videos, even with the lowest privileges. I am starting to get more comfortable with the idea of letting people who are filling in get temporary access to the channel to do the recording as long as they are trusted. I may also set up something to backup the video files in a way so we don't have to fear deletion.

**Comment by bmann** [comment] 2019-04-04 16:48
@lrettig no to separate AllCoreDevs blog twitter etc — this is busy work that already isn’t handled as well as it should, and I’m pretty sure ACD would NOT want this. It really is a coordination channel and we’re adding more overhead. 

I treat EthMagicians as my community blog. Having an Announcements channel or process is possible as well. 

Also — this is all OT, file new issues and/or kick off discussion in the forum for further discussion. 

Technically this is documentation issue, plus ideally @timbeiko & @Souptacular supporting each other.

**Comment by Souptacular** [comment] 2019-04-05 19:44
Auryn has volunteered to record the meeting this next week and he helped me with some ways we can better make sure that people can easily stream to the EF YouTube channel in the future.

**Comment by mariapaulafn** [comment] 2019-04-05 20:52
Hey @Souptacular for emergencies - I have tried this transcribing service that's really accurate, and not expensive. If at some point we cannot find a note taker - if the call is recorded I can send it there and clean them up, I was really surprised with the accuracy. https://gotranscript.com/

**Comment by mariapaulafn** [comment] 2019-04-05 20:54
@lrettig there is an ETHMagicians Medium Blog. We just hardly use it :) 
Can give you access @timbeiko https://medium.com/ethereum-magicians/

**Comment by bmann** [comment] 2019-04-06 04:59
@Souptacular can we get some of this documented? Questions are on the wiki. 

Some of it maybe not because of IPSec concerns but in general should know some people / who to contact if anything needed.

**Comment by bmann** [comment] 2019-04-06 21:09
I'm adding the open questions from the wiki (I justed edited them based on some answers here):

* who has commit access / can manage issues on the `ethereum/pm` repo
* what is the setup for YouTube livestreaming? anything that needs documenting?

Would love to close this if we can get these two last items answered. :)

**Comment by timbeiko** [comment] 2019-06-11 18:16
@Souptacular you mentioned that Auryn helped with "some ways we can better make sure that people can easily stream to the EF YouTube channel in the future."

Is this documented anywhere? 

Also, do you have an update on @bmann's questions above?

Thanks!

**Comment by lrettig** [comment] 2019-06-15 16:54
> who has commit access / can manage issues on the ethereum/pm repo

@cdetrio, @vbuterin, @souptacular, @5chdn, and myself

> what is the setup for YouTube livestreaming? anything that needs documenting?

Hudson put together a document and shared it with me before - will let him share it here.

**Comment by timbeiko** [comment] 2019-06-17 13:55
Cool, once that document is shared, if it can be, then we can close this. We can follow up with Hudson on the next call if he's there.

**Comment by Souptacular** [comment] 2019-06-21 05:43
Here is the doc! Comments on it are left open.

https://docs.google.com/document/d/1dF_Drs56ErV6wJgFmbzpdN-cINshKCsB61D92NS2JDg/edit

Idk where it should go permanently so people can reference it.

**Comment by lrettig** [comment] 2019-06-21 10:52
> Idk where it should go permanently so people can reference it.

Maybe we can move it into an ECH github repo or wiki?

**Comment by timbeiko** [comment] 2019-06-21 12:40
As much as I'd like to see the ECH Repo become the default place for issues, given that this specifically relates to calls whose agenda are in `ethereum/pm`, perhaps having it as a markdown file there with the contents from this doc makes the most sense. What do you think?

**Comment by lrettig** [comment] 2019-06-22 09:42
> What do you think?

Move `ethereum/pm` to `ethereum-cat-herders` :)

**Comment by timbeiko** [comment] 2019-06-25 15:42
Just opened https://github.com/ethereum/pm/pull/108 and accidentally already merged the change on this repo, [here](https://github.com/ethereum-cat-herders/PM/commit/69f915f312c69a4685d2548e7c807aeec3e2428f)

**Closed by timbeiko** 2019-06-25 15:42 UTC
