### ISSUE TITLE
[State-Rent] Evaluate if Linear Storage Backed is correct.

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#47] opened 2019-04-18 01:17 UTC
Notes:
 * Could be better for the EWASM implementation as Linear Storage is part of that spec. Increasing operability with existing libraries. Example using a Red-Black Tree implementation compiled from another language using linear storage.
 * Most developers already think in Arrays over Maps. Unnecessary internal complexity arises from implementations where Devs use an array because traditionally arrays are simpler where currently the inverse is true.

**Comment by lrettig** [comment] 2019-04-25 17:34
This is being tracked from the Ewasm side here: https://github.com/ewasm/design/issues/188

**Comment by timbeiko** [comment] 2019-07-31 18:22
@lrettig should we close this as a duplicate of your ewasm issue?

**Comment by lrettig** [comment] 2019-08-09 21:02
👍

**Closed by lrettig** 2019-08-09 21:02 UTC
Labels: Ewasm, State Fees
